### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by KasaiKonoru** [Tharki-God/ReJoinVC#1]
![grafik](https://user-images.githubusercontent.com/45830738/224492951-2e7c8b8a-2f54-4cd7-a769-b8d4f4411fc1.png)
Pls help me. How I need to do this?

**Comment by yofukashino** [comment]
retry now

**Comment by KasaiKonoru** [comment]
yeah nice thx

**Comment by KasaiKonoru** [comment]
what you changed?

**Comment by yofukashino** [comment]
> what you changed?

Released the plugin. You tried when I just copied plugin template to work on
